

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - /home/${USER}/data/wordpress:/var/www/wordpress:ro   
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - /home/${USER}/data/mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - /home/${USER}/data/wordpress:/var/www/wordpress     
    networks:
      - inception
    restart: always

networks:
  inception:
    driver: bridge




