version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
    - mariadb
    networks:
      - inception

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - /home/${USER}/data/mariadb:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge




