

services:
  nginx:
    build: ./requirements/nginx
    image: nginx:custom
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:custom
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:custom
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/wordpress     
    networks:
      - inception
    restart: always

volumes:
  mariadb:
    name: mariadb  
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/mariadb
      o: bind

  wordpress:
    name: wordpress  
    driver: local
    driver_opts:
      type: none
      device: /home/${USER}/data/wordpress
      o: bind

networks:
  inception:
    driver: bridge




