version: '3.8'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - inception
    restart: always
networks:
  inception:
    driver: bridge
